%____________________________________________________________________
%                       HEBER LAVAO
%                       Control Predictivo basado en Datos (DeePC Robusto)
%                       enfoque incremental para un MotorDC
%                       aplicando Variables inbstrumentales (IV)
%                       aplicando descomposicion de valores singulares (SVD, opcional)
%                       2026
% REFERENCIAS  (software)        
%           December 2023, Sohrab Rezaei, Ali Khaki-Sedigh, 
%           Data-Enabled Predictive Control (DeePC)
%           Software Generated by Sohrab Rezaei
%           https://www.mathworks.com/matlabcentral/fileexchange/166376-comparative-analysis-of-data-driven-predictive-control-strat/files/LICENSE?s_tid=prof_contriblnk
%
%           November 2023, Kai Zhang, Data-Enabled Predictive Control (DeePC)
%           Software Generated by iamKaiZhang
%           https://github.com/iamKaiZhang/DeePC
%
% Funcion de costo matricial
% J=||Yfg-r||_Q^2+||delta_Ufg||_R^2+ lambda_g||g||^2+lambda_y||sigma_y||^2
%
% Funcion de costo en tiempo k
%   J = sum_{ k=0}^{N-1} (||y_k - r_k||_Q² + ||delta_u_k||_R²)
%   + lambda_g||g||^2+lambda_y||sigma_y||^2;
%
% Np  : cantidad de muestras en la secuencia de PRBS
% uu  : variable delta_u
% Q   : peso de salida (l x l)
% R   : peso de control (nu x nu)
% N   : horizonte de predicción
% nu  : número de entradas (control)
% ny  : número de salidas
% r,rd, ref   : referencia a seguir (l*N x 1 vector)
% m   : longitud del vector de restricciones de entrada
% p   : longitud del vector de restricciones de salidas
% H   : matriz Hankel 
% h   : matriz Hessiana (simétrica)
% f   : vector lineal (para quadprog, -2*r'*Q)
%%------------------------------------------------------------------
function [u, y_pred, sigma_y]=DEEPC_H(u_data_i, y_data_i,u_IV, y_IV,ref,umin,umax,ymin,ymax,lambda_g, lambda_y,Qm,Rm, N, T_ini)     
    L = N+T_ini;
    larg=size(u_data_i,2); % total datos recolectados +T_ini
    tama = larg-T_ini; %datos para hankel
    cols=tama-L+1;%dimension hankel
    n=cols+T_ini;  
    nu=1;
    ny=1;
    l_u = nu*N;
    l_y = ny*T_ini;
    m=2*l_u;
    q=2*l_y;
    h = eye(n);
    f = zeros(n, 1);
    Aineq =zeros(m,n);
    bineq = zeros(m,1);
    Aeq = zeros(q,n);
    beq = zeros(q,1);
    lb = zeros(n,1);
    ub = zeros(n,1);
    R_m = kron(eye(N), Rm);
    Q_m = kron(eye(N), Qm);
    ref = ref/ymax;
    u_data = u_data_i/umax;
    y_data = y_data_i/ymax;
    u_ini = u_data(:, end-T_ini+1:end);
    y_ini = y_data(:, end-T_ini+1:end);
    %datos variable instrumental normalizacion
    u_IVd = u_IV/umax;
    y_IVd = y_IV/ymax;
    %generar matrices
    U_p = u_data(:,1:tama);
    Y_p = y_data(:,1:tama);
    H_Up = make_hankel(U_p,L); %bloque pasado longitud= N+T_ini
    H_Yp = make_hankel(Y_p,L); %contiene bloque pasado T_ini y el bloque 
    %variable instrumental
    IV_Up = make_hankel(u_IVd,L); 
    IV_Yp = make_hankel(y_IVd,L);
    H_1 = [H_Up; H_Yp]; %matriz de datos
    % Aplicar variable instrumental no incluye Yf
    H_2yp = IV_Yp(1:T_ini, :);
    H_2 = [IV_Up; H_2yp];
    H = SVD(H_2);%descomposicion en valores singulares (opcional)
    Z = H; %variable instrumental
    %proyeccion de Z
    PZ=Z'*((Z*Z')\Z);
    IV_H = (H_1*PZ); %./tama; %(/tama es opcional) pesos cambian 
    %bloques de la nueva matriz para solver
    Hup = IV_H(1:T_ini, :);
    Huf = IV_H(T_ini+1:L, :); %bloque futuro longitud = N
    Hyp = IV_H(L+1:L+T_ini, :);
    Hyf = IV_H(L+T_ini+1:end, :); %T_ini+1:end = hay N filas
    %cr4eacion de matrices para el solver   
    l_g = size(IV_H,2); %dimension del vector g%bloque g
    term1 = Hyf' * Q_m * Hyf;
    term2 = Huf' * R_m * Huf;
    eig1 = eig(term1);
    eig2 = eig(term2);
    min_eig1 = max(min(eig1), 0);
    min_eig2 = max(min(eig2), 0);
    min_eig = max(min_eig1, min_eig2);
    % Regularización MUY agresiva
    % lambda_g comparable al eigenvalor mínimo
    lambda_gn = max(10 * min_eig, lambda_g);
    %hg mejor lambda_g
    hg = term1 + term2 + real(lambda_gn) * eye(l_g);
    %hg = Hyf'*Q_m*Hyf + Huf'*R_m*Huf + lambda_g*eye(l_g); %bloque hessiana lambda_g*I
    %cond(hg)
    hsigma = lambda_y*eye(ny*T_ini); %bloque hessiana lambda_y*I
    %hessiana completa
    h(1:l_g,1:l_g) = hg;
    h(l_g+1:end,l_g+1:end) = hsigma; 
    %restricción sum(g) = 1
    fila_suma_g = [ones(1, l_g), zeros(1, ny * T_ini)];
    %desigualdades
    Aineq(1:N,1:cols) = Huf;
    Aineq(N+1:2*N,1:cols) = Hyf;
    Aineq(2*N+1:3*N,1:cols) = -Huf;
    Aineq(3*N+1:4*N,1:cols) = -Hyf;
    u_max_v = repmat((umax/umax),N,1); %
    y_max_v = repmat((ymax/ymax),N,1); %
    u_min_v = repmat((umin/umax),N,1); %
    y_min_v = repmat((ymin/ymax),N,1); %
    bineq = [u_max_v;
             y_max_v;
            -u_min_v;
            -y_min_v];
    %restricciones     
    lb_g = ones(l_g,1)*(-1000);
    ub_g =  ones(l_g,1)*1000;
    lb_sigma = ones(ny*T_ini,1)*(-1000); %zeros(ny*T_ini,1);
    ub_sigma = ones(l_y,1)*1000;
    lb(1:l_g,:) = lb_g;
    ub(1:l_g,:) = ub_g;
    ub(l_g+1:n,:) = ub_sigma;
    lb(l_g+1:n,:) = lb_sigma;
    %igualdades
    Aeq(1:T_ini,1:l_g) = Hup;
    Aeq(T_ini+1:q,1:l_g) = Hyp;
    Aeq(T_ini+1:q,l_g+1:n) = -eye(ny*T_ini);
    Aeq=[Aeq; fila_suma_g];
    b1=reshape(u_ini,[],1);
    b2=reshape(y_ini,[],1);
    beq = [b1;b2;1]; 
    %referencia
    rd = ones(N,1).*ref; %referencia x10
    f(1:l_g,1) = -Hyf'*Q_m*rd;
    h = (h + h') / 2; % fuerza simetrìa
    x = quadprog(h,f,Aineq,bineq,Aeq,beq,lb,ub,[]);
        g=x(1:l_g,1);
        sigma_y = x(l_g+1:end,1) .* (ymax-ymin)+ymin;
        u_pred = Huf*g;
        u = u_pred .* umax;
        y_pred = (Hyf*g) .* (ymax-ymin)+ymin;
end