%____________________________________________________________________
%                       HEBER LAVAO
%                       Control Predictivo basado en Datos (DeePC Robusto)
%                       coulson et al.
%                       enfoque incremental para un MotorDC
%                       aplicando Variables inbstrumentales (IV)
%                       aplicando descomposicion de valores singulares (SVD, opcional)
%                       2026
% REFERENCIAS          
%           December 2023, Sohrab Rezaei, Ali Khaki-Sedigh, 
%           Data-Enabled Predictive Control (DeePC)
%           Software Generated by Sohrab Rezaei
%           https://www.mathworks.com/matlabcentral/fileexchange/166376-comparative-analysis-of-data-driven-predictive-control-strat/files/LICENSE?s_tid=prof_contriblnk
%
%           November 2023, Kai Zhang, Data-Enabled Predictive Control (DeePC)
%           Software Generated by iamKaiZhang
%           https://github.com/iamKaiZhang/DeePC
%SOFTWARE: 
% MATLAB 2015
%%-----------------------------------------------------------------
clear mex; clear all; clc; close all;
%% Datos ingreso sistema
%analisis de respusta transitoria
T_s=0.3; %tiempo de muestreo de la simulacion
sT = 15.5; %tiempo de establecimiento
t_r = 0.771; %risetime
nr =  12; % numero de regisros de PRBS 
Amp = 10; % Amplitud de señal (maxima pàra u del sistema)
nu = 1; % entradas del sistema
ny = 1; % salidas del sistema
n = 7; %orden sys_ss, variables del sistema (2) + estados de retardo (5)
T_ini =8; %debe ser mayor a n y n>=al retardo del sistema
N =20; % horizonte
Q_d = 20; %Q peso de las entradas
R_d = 0.1; %R peso de las salidas
lambda_g = 0.001; % Peso de regularizacion
lambda_y = 1E10;% peso del slack 
d =5; %número de muestras de retardo del sistema
%% definir registros y variables
Mpas = 1; %aplicacion de intervalo u
Sf = 1.1;        % Factor de seguridad PRBS
%% PRBS
%PRBS9 polinomio x9 + x5 +1
Np = 2^nr-1; % Longitud de la secuencia de PRBS
%calculo de T_sw
T_sw = sT/(1.1*nr);% ajuste del intervalointervalo de muestreo PRBS
% 2. Verificación por Rise Time (Alta frecuencia)
w_high = 4 * Sf / t_r;   % Estimación de frecuencia máxima [5]
T_sw_max = 2.8 / w_high; % Límite superior para T_sw [7]
% Si el T_sw de la ganancia es muy lento para el rise time, se ajusta
if T_sw > T_sw_max
    T_sw = T_sw_max;
end
% relacion tiempo PRBS y tiempo simulacion
TTF = round(T_sw/T_s); %cantidad de muestras en cada cambio de PRBS
if TTF==0
    fprintf('error: TTF debe ser igual o mayor a 1 \n');
end
T_sw = TTF*T_s; %recalculo de T_sw para sincronizacion
times = T_sw*Np; % tiempo de la secuencia en segundos
Sec = TTF*Np;
fmin = 1/(Np*T_sw); % calculo del las frecuencias de PRBS
fmax = 2.8/(2*pi*T_sw);
fprintf('la PRBS tiene f minima es %d, y la f maxima %d \n', fmin, fmax);
%% tiempo de simulacion
reg = zeros(1,Np); % crear el registro de longitud Np
%% setup del sistema
% límites con margen de seguridad
u_max = 100; % límite de control
u_min = 0; 
y_max = 200;
y_min = 0;
%limites de incremento u
umax =5; % límite de control (amp PRBS)
umin = -5;
L = T_ini + N;
% buffer de simulacion retardo   
buffer_u = zeros(nu,d);
%% simulacion de control DeePC
T_min = ((nu+1)*(T_ini+N+(n-d))-1); %minimo datos 
T_ex = round(T_min/T_sw);
larg = T_ex + T_ini;
cols =larg-L+1;
max_samples = larg;
%inicializacion de vectores
y_data = zeros(ny,larg);
u_data = zeros(nu,larg);
u_final = [];
y_final = [];
y_fpred = [];
x_final = [];
y_1 = zeros(ny, Mpas);
x_1 = zeros(n, Mpas);
x0 = zeros(cols, 1);
t_final=[];
r_final=[];
u_n=[];
Ju=0;
sigma_y = 0;
% r_final = u;
cost_temp = [];
%% secuencia de referencia (señal deseada).
r1 = 0*2*pi/60*ones(1,5*TTF);
r2 = 200*2*pi/60*ones(1,10*TTF);
r3 = 400*2*pi/60*ones(1,2*TTF);
r4 = 800*2*pi/60*ones(1,25*TTF);
r5 = 477.4248*2*pi/60*ones(1,15*TTF);
r6 = 200*2*pi/60*ones(1,10*TTF);
r7 = 0*2*pi/60*ones(1,17*TTF);
r8 = 300*2*pi/60*ones(1,25*TTF);
r_sec = [r5 r5 r4 r4 r5 r5 r6 r6 r6 r8 r8 r5 r5 r2 r2];
r_data = [r1 r_sec]; %señal prueba step
%% DeePC Controller Setup z=[g,sigma_y]
simulax = max_samples+size(r_data,2)-N-2;
%sistema en espacio de estados de motor DC
J = 0.3795;      % kg·m²
b = 0.006803; % 0.06803; % N·m·s/rad
Km = 2.401;      % V·s
Ra = 38.9;       % Ohm
La = 0.3685;     % H
Kpwm =3.901;  % 2.931; %  %/V
T_s = 0.3;  % Tu tiempo de muestreo
d = 5;
% Función de transferencia (CONTINUA)
num = Kpwm * Km;
den = [J*La, J*Ra + b*La, b*Ra + Km^2];
sys_teorico_cont = tf(num, den);
%Espacio de estados 
A = [-Ra/La,-Km/La; Km/J, -b/J];
B = [Kpwm/La; 0];
C = [0, 1];
D=0;
% Discretizar si es necesario (para comparar en el mismo dominio)
sys_teorico_c = ss(A, B, C, D);
sys_teorico_d = c2d(sys_teorico_c, T_s);
% matrices discretas
[Ad,Bd,Cd,Dd] = ssdata(sys_teorico_d);
%aplicar retardo
[Aa,Ba, Ca, Da] = anadir_retardo_u(Ad, Bd, Cd, Dd, d);
% nuevo sistema discreto aumentado
sys_delay = ss(Aa,Ba,Ca,Da,T_s);
%crear el sistema discreto_teorico
Ad = sys_delay.A;
Bd = sys_delay.B;
Cd = sys_delay.C;
Dd = sys_delay.D;

%Matriz de perturbacion
E = zeros(n,1);
E(2,1) = -1/J;
%% Simulacion del DeePC
for k = 1:simulax
    %generacion de señal PRBS
    if k==1
         [u_prbs, u_total] = generar_PRBS_para_identificacion(TTF, larg, Amp, u_min, u_max);
    end
    for i = 1:Mpas
      t=1*T_s;
      if mod(k, larg)==0 || k==1 %reinicia bit_prbs
          bit_prbs = 1;
      end  
      if isempty(u_n) %señal de prbs durante la prueba inicial
          uu = u_total(bit_prbs);
      else %señal aplicada a sistema cuando se ha iniciado el control
         uu = u_n(i,:)+ u_final(end);
      end
      bit_prbs = bit_prbs + 1;
      %añadir perturbacion
      if k >= max_samples+100 
          d_k = 1;   % par de carga
      else
          d_k = 0;
      end
      %sistema
        y_1 = Cd * x_1(:, i) + Dd * uu;          
        x_1 = Ad * x_1(:, i) + Bd * uu + E*d_k;  

        x_1(:, i+1) = x_1(:, i); %almacena el ultimo valor calculado en la matriz 
        y_1(:, i) = Cd * x_1(:, i) + 0.7*randn();%adiciona ruido
        Ju = Ju + uu*R_d*uu'; %costo
    end
    %almacena vector de tiempo
    if isempty(t_final)
      t_final = T_s;             
    else
      t_final = [t_final, t_final(end)+T_s];
    end 
    %actualiza vectores de registro
    y_final = [y_final y_1];
    u_final = [u_final uu];
    x_final = [x_final x_1];
    x_1(:, 1) = x_final(:, end);
        
    if k == (max_samples) %iniciales de control iter 1           
      r_final = u_total(1,1:max_samples);
      y_data = y_final(:, end-max_samples+1:end-T_ini);
      y_IV = y_data;
      u_data = u_final(:, end-max_samples+1:end-T_ini+1);
      du_data = diff(u_data);%calculo de incrementales historicos
      u_IV = du_data;
    else if k > max_samples
      u_data_o = u_final(:, end-max_samples:end-T_ini); %uno mas par el diff()
      y_data_o = y_final(:, end-max_samples+1:end-T_ini);
      du_data_o =  diff(u_data_o);%calculo de incrementales historicos
      u_ini = u_final(:,end-T_ini:end); 
      du_ini = diff(u_ini);%calculo de incrementales iniciales
      u_data_f = [du_data, du_ini];
      y_ini = y_final(:,end-T_ini+1:end);
      y_data_f = [y_data, y_ini];
      rd = reshape(r_data(:,k-max_samples:k-max_samples+N-1),[],1);
      ref=rd(1);
      ref_s=ref-sigma_y(end);
      r_final = [r_final ref]; %actualiza vector referencia
      tic
      [u, y_pred, sigma_y] = DEEPC_H(u_data_f, y_data_f, u_IV, y_IV, ref_s, umin,umax,y_min,y_max,lambda_g, lambda_y,Q_d,R_d, N, T_ini);
      toc
      fprintf('\t tiempo solver= %d \n',  toc);
      y_fpred = [y_fpred, y_pred(1)]; %actualiza el vector y_pred
      u_n = u;
      Q_m = kron(eye(N), Q_d);
      cost_inst = (y_pred(1:N)-rd)'*Q_m*(y_pred(1:N)-rd);
      cost_temp = [cost_temp, cost_inst];
        end 
    end
end
cost_final=[zeros(1,max_samples) cost_temp];
% graficar todo
figure
subplot(2,1,1)
plot(t_final, r_final, 'k--', 'LineWidth', 1.5)
hold on
plot(t_final, y_final, 'r', 'LineWidth', 2)
grid on
legend('Referencia (r)', 'Salida (y)')
ylabel('Amplitud')
title('Seguimiento de Referencia')
subplot(2,1,2)
[ax,h1,h2] = plotyy(t_final, u_final, t_final, cost_final);
set(ax(1),'YColor','b')
set(ax(2),'YColor','m')
linkaxes(ax,'x')
set(h1,'Color','b','LineWidth',1.5)
set(h2,'Color','m','LineWidth',1.5)
ylabel(ax(1),'Control (u)')
ylabel(ax(2),'Costo acumulado')
xlabel('Tiempo (s)')
grid(ax(1),'on')
legend([h1 h2],{'Control (u)','Costo'})
title('Esfuerzo de Control y Función de Costo')